### ISSUE TITLE
ECMA 6 Support

### ISSUE THREAD

**Issue by iamdcamp** [calebthebrewer/jsenvy#12]
Feature Request: Support for ECMA 6. i.e. block scoping, arrow functions, template literals, etc.

**Comment by cazzer** [comment]
Thanks for the request, @iamdcamp! JSEnvy uses your browsers interpreter, so technically some of these features are already supported 😄. Check out [arrow functions and template literals](http://jsenvy.com/#logs=var%20a%20%3D%20()%20%3D%3E%20(%20%60arrow%20functions%20and%20template%20literals%20%24%7Btrue%20%3F%20'are'%20%3A%20'aren%5C't'%7D%20supported!%60)%2C%2Ca()) in action, (assuming you're on a somewhat current browser).

**Comment by iamdcamp** [comment]
Thanks @cazzer! What originally led me to think there was an issue was that assignments using `let` and `const` were returning `undefined`. 

Aaaand so TIL: 
[MDN on `const`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const): "Global constants do not become properties of the window object, unlike var variables."
[MDN on `let`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let): "At the top level of programs and functions, let, unlike var, does not create a property on the global object."
